version: '3.8'

services:
  db_postgres:
    image: postgres:15-alpine
    container_name: postgres_bot
    restart: always
    # O Docker vai carregar o arquivo .env automaticamente para este serviço
    env_file:
      - .env
    environment:
      # Aqui dizemos que a variável do Postgres recebe o valor que está no .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - bot_pg_data:/var/lib/postgresql/data

  app_bot:
    build: .
    container_name: node_bot
    restart: always
    depends_on:
      - db_postgres
    env_file:
      - .env
    environment:
      - DB_HOST=db_postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  bot_pg_data: