# Estágio 1: Build (Instala as dependências de forma isolada)
FROM node:20-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install

# Estágio 2: Execução (Imagem final, leve e segura)
FROM node:20-slim
WORKDIR /app

# Instala ferramentas necessárias para o Puppeteer/Baileys caso precise futuramente
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libnss3 \
    libatk-bridge2.0-0 \
    libxcomposite1 \
    libxrandr2 \
    libxdamage1 \
    libgbm1 \
    libasound2 \
    libpangocairo-1.0-0 \
    libcups2 \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Copia apenas os módulos prontos do Estágio 1
COPY --from=builder /app/node_modules ./node_modules
# Copia o restante do seu código
COPY . .

# Expõe a porta da sua Dashboard
EXPOSE 3000

# Comando que inicia o sistema
CMD ["node", "index.js"]